---
services:
  app:
    depends_on:
      - db
      - solr
    image: dromedary
    build:
      dockerfile: Dockerfile
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "127.0.0.1:3000:3000" # Rails
      - "1111:1111"
      - "1234:1234" # RubyMine
      - "26162:26162" # RubyMine
    environment:
      - SOLR_ROOT=http://solr:8983/
      - SOLR_COLLECTION=med-preview
      - SOLR_COLLECTION_BASE=med
      - SOLR_USERNAME=solr
      - SOLR_PASSWORD=SolrRocks
      - SOLR_REPLICATION_FACTOR=1
      - DATA_ROOT=/mec/data
      - BUILD_ROOT=/mec/data/build
    volumes:
      - .:/opt/app
      - data:/mec/data
    command:
      - bin/rails
      - s
      - -b
      - 0.0.0.0

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - db:/var/lib/postgresql/data

  solr:
    build: solr/.
    ports:
      - "9090:8983"
    environment:
      - ZK_HOST=zoo:2181
    depends_on:
      - zoo
    command: solr-foreground

  zoo:
    image: zookeeper
    ports:
      - 9091:2181
    environment:
      ZOO_MY_ID: 1

volumes:
  data:
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
  db:
  solr:
    driver_opts:
      type: none
      device: ${PWD}/solr_data
      o: bind

