---
services:
  #  web:
  #    image: dromedary-web
  #    build:
  #      context: .
  #      dockerfile: Dockerfile.prod
  #    ports:
  #      - "3000:3000"
  #    environment:
  #      - DATA_FILE=/usr/src/app/All_MED_and_Bib_files.zip
  #      - PROMETHEUS_PUSH_GATEWAY=http://pushgateway:9091
  #      - SOLR_URL=http://nectar.umdl.umich.edu:8081/solr/dromedary_testing/
  #      - REDIS_URL=redis://redis:6379
  #      - DEBUG_ENV=true
  app:
    depends_on:
      - db
      - solr
      - redis
    image: dromedary
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000" # Rails
      - "1234:1234" # RubyMine
      - "26162:26162" # RubyMine
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/opt/app
      - data:/var/opt/app/data
      - gems:/var/opt/app/gems
  db:
    ports:
      - "5432:5432"
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/db

    volumes:
      - db-data:/var/lib/postgresql/data
  solr:
    platform: linux/x86_64
    image: ghcr.io/mlibrary/dromedary/dromedary-solr:arm64
    ports:
      - "8983:8983"
    environment:
      - SOLR_JAVA_MEM=-Xms1024m -Xmx1024m
      - SOLR_HEAP=1024m
    volumes:
      - solr-conf:/opt/solr/server/solr/configsets/dromedary
      - solr-data:/var/solr
  redis:
    image: redis:6-buster
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  sidekiq:
    depends_on:
      - db
      - solr
      - redis
    image: dromedary
    ports:
      - 3001:3001
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/opt/app
      - data:/var/opt/app/data
      - gems:/var/opt/app/gems
    command:
      - sleep
      - infinity
#    command:
#      - bundle
#      - exec
#      - sidekiq
#      - -r
#      - ./app/jobs/job_index.rb
#      - solr_core:/opt/solr/server/solr/dromedary
#  data:
#    build:
#      dockerfile: data.Dockerfile
#      context: .
#    volumes:
#      - ../data:/opt/app-data
#      - gem_cache:/gems
#  redis:
#    image: redis:6-buster
#    ports:
#      - 6380:6379
#
#  sidekiq:
#    image: dromedary-web
#    ports:
#      - 3001:3001
#    command:
#      - bundle
#      - exec
#      - sidekiq
#      - -r
#      - ./app/jobs/job_index.rb
#    environment:
#      - REDIS_URL=redis://redis:6379
#      - SOLR_URL=http://nectar.umdl.umich.edu:8081/solr/dromedary_testing/
#      - DATA_FILE=/opt/app-data/All_MED_and_Bib_files.zip
#      - PROMETHEUS_PUSH_GATEWAY=http://pushgateway:9091
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
volumes:
  data:
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
  gems:
  db-data:
  solr-conf:
    driver_opts:
      type: none
      device: ${PWD}/solr/dromedary
      o: bind
  solr-data:
  redis-data:
