version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATA_FILE=/usr/src/app/All_MED_and_Bib_files.zip
      - PROMETHEUS_PUSH_GATEWAY=http://pushgateway:9091
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
  solr:
    image: solr:6.6.5
    ports:
      - "8983:8983"
    volumes:
      - solr_core:/opt/solr/server/solr/dromedary
#  data:
#    build:
#      dockerfile: data.Dockerfile
#      context: .
#    volumes:
#      - ../data:/opt/app-data
#      - gem_cache:/gems
  redis:
    image: redis:6-buster
    ports:
      - 6380:6380

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

volumes:
  gem_cache:
  solr_core:
