apiVersion: batch/v1
kind: Job
metadata:
  name: data
spec:
  template:
    spec:
      containers:
        - name: data
          image: ghcr.io/mlibrary/dromedary/dromedary_data:20220225.5
          imagePullPolicy: Always
          command:
            - ./index_data.sh
          env:
            - name: SOLR_URL
              value: http://solr:8983/solr/dromedary_testing/
      restartPolicy: Never
  backoffLimit: 1