apiVersion: batch/v1
kind: Job
metadata:
  name: data
spec:
  template:
    spec:
      containers:
        - name: data
          image: ghcr.io/mlibrary/dromedary/dromedary_data:20220225.5
          imagePullPolicy: Always
          command:
#            - ls
            - ./index_data.sh
      restartPolicy: Never
      imagePullSecrets:
        - name: regcred
  backoffLimit: 1