development:
  adapter: async

test:
  adapter: async

production:
  adapter: <%= Dromedary::Services.cable.adapter %>
  url: <%= Dromedary.config.cable.url %>
  channel_prefix: <%= Dromedary.config.cable.channel_prefix %>

