blacklight:
  adapter: solr
  url: <%= Services[:solr_url] %>

solr:
  url: <%= Services[:solr_url] %>

secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "somesecretkey" %>



db:
  url: unused

cable:
  adapter: async
  url: unused
  channel_prefix: dromedary


relative_url_root: <%= ENV["RAILS_RELATIVE_URL_ROOT"] || "/" %>

data_dir: <%= Services[:data_directory] || "#{Rails.root}/data" %>
build_root: <%= Services[:build_root] || "#{Rails.root}/data/build" %>

log_dir: <%= Services[:log_dir] || "./log" %>