---
name: "Build unstable image"

on:
  workflow_dispatch:  # This allows to kick-off the action manually from GitHub Actions

jobs:
  build-unstable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 'ghcr.io/mlibrary/dromedary/dromedary-unstable:${{ github.sha }}'
          file: ./Dockerfile
          target: production
          build-args: |
            RAILS_RELATIVE_URL_ROOT=/m/middle-english-dictionary
