name: Build main

on:
  push:
    # When merged this should end up being branches: [master] (or,
    # better yet, branches: [main]).
    branches:
    - kubernetes

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - webapp
        - assets
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.prod
        target: ${{ matrix.target }}
        push: true
        tags: |
          ghcr.io/mlibrary/dromedary/dromedary_unstable_${{ matrix.target }}:latest
          ghcr.io/mlibrary/dromedary/dromedary_unstable_${{ matrix.target }}:${{ github.sha }}

  deploy-assets-testing:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Assets to Testing
      uses: mlibrary/deploy-to-kubernetes@v3
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/mlibrary/dromedary/dromedary_unstable_assets:${{ github.sha }}
        cluster_ca: ${{ secrets.HATCHER_CLUSTER_CA }}
        cluster_server: https://hatcher.kubernetes.lib.umich.edu
        namespace_token: ${{ secrets.HATCHER_TEST_TOKEN }}
        namespace: middle-english-testing
        resource_name: assets
        container: nginx

  deploy-webapp-testing:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Webap to Testing
      uses: mlibrary/deploy-to-kubernetes@v3
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/mlibrary/dromedary/dromedary_unstable_webapp:${{ github.sha }}
        cluster_ca: ${{ secrets.HATCHER_CLUSTER_CA }}
        cluster_server: https://hatcher.kubernetes.lib.umich.edu
        namespace_token: ${{ secrets.HATCHER_TEST_TOKEN }}
        namespace: middle-english-testing
        resource_name: webapp
        container: '*'
